Repository medhost/fhir-works-on-aws-persistence-ddb, pull requests merged in 2021-02, with the labels that each got.

#14 Mainline multitenancy sync.
  .github/workflows/labeler.yml
  CHANGELOG.md
  package.json
  src/dataServices/dynamoDbBundleService.test.ts
  src/dataServices/dynamoDbBundleService.ts
  src/dataServices/dynamoDbBundleServiceHelper.ts
  src/dataServices/dynamoDbDataService.test.ts
  src/dataServices/dynamoDbDataService.ts
  src/dataServices/dynamoDbHelper.test.ts
  src/dataServices/dynamoDbHelper.ts
  src/dataServices/dynamoDbParamBuilder.test.ts
  src/dataServices/dynamoDbParamBuilder.ts
  src/dataServices/dynamoDbUtil.test.ts
  src/dataServices/dynamoDbUtil.ts
  src/ddbToEs/ddbToEsHelper.ts
  testUtilities/ConditionalCheckFailedException.ts
  testUtilities/GenerateStagingRequestsFactory.ts
  yarn.lock
Labels: size/xl

#15 missing yarn file update.
  yarn.lock
Labels: size/xs

#16 Multitenancy develop sync.
  .github/workflows/labeler.yml
  CHANGELOG.md
  package.json
  src/dataServices/dynamoDbBundleService.test.ts
  src/dataServices/dynamoDbBundleService.ts
  src/dataServices/dynamoDbBundleServiceHelper.ts
  src/dataServices/dynamoDbDataService.test.ts
  src/dataServices/dynamoDbDataService.ts
  src/dataServices/dynamoDbHelper.test.ts
  src/dataServices/dynamoDbHelper.ts
  src/dataServices/dynamoDbParamBuilder.test.ts
  src/dataServices/dynamoDbParamBuilder.ts
  src/dataServices/dynamoDbUtil.test.ts
  src/dataServices/dynamoDbUtil.ts
  src/ddbToEs/ddbToEsHelper.ts
  testUtilities/ConditionalCheckFailedException.ts
  testUtilities/GenerateStagingRequestsFactory.ts
  yarn.lock
Labels: size/xl

#18 Medhost develop#sync multitenancy
  src/dataServices/dynamoDbDataService.test.ts
  src/dataServices/dynamoDbParamBuilder.test.ts
Labels: size/m

#17 [YCU-51043] - add multitenancy support for bundles
  src/dataServices/dynamoDbDataService.test.ts
  src/dataServices/dynamoDbParamBuilder.test.ts
Labels: size/m
